import React, { useState } from 'react';
import { EasmScanResult, SecurityFinding, Severity } from '../types';
import { 
  ShieldAlert, ShieldCheck, AlertTriangle, Info, CheckCircle2, 
  Download, Copy, ExternalLink, ArrowUpRight, Sparkles, Layers,
  Server, Globe, Mail, Lock, FileText, Check, ChevronDown, 
  Search, Shield, Cpu, Terminal, ArrowDown
} from 'lucide-react';
import { DigitalFootprintTab } from './DigitalFootprintTab';
import { SecurityPostureTab } from './SecurityPostureTab';
import { MitreMatrixTab } from './MitreMatrixTab';
import { AiThreatReportTab } from './AiThreatReportTab';
import { ComplianceReportTab } from './ComplianceReportTab';
import { VulnerabilitiesTab } from './VulnerabilitiesTab';
import { Scale, Award, Flame, Bug } from 'lucide-react';
import { getControlsForFinding } from '../utils/complianceEngine';

interface UnifiedScanReportProps {
  scan: EasmScanResult;
  onNavigateTab: (tab: string) => void;
}

const SEVERITY_CONFIG: Record<Severity, { bg: string; text: string; border: string; icon: React.ReactNode }> = {
  CRITICAL: {
    bg: 'bg-red-50/70 dark:bg-red-950/30',
    text: 'text-red-700 dark:text-red-400',
    border: 'border-red-200 dark:border-red-900/60',
    icon: <ShieldAlert className="w-4 h-4 text-red-600 dark:text-red-400" />
  },
  HIGH: {
    bg: 'bg-orange-50/70 dark:bg-orange-950/30',
    text: 'text-orange-700 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-900/60',
    icon: <AlertTriangle className="w-4 h-4 text-orange-600 dark:text-orange-400" />
  },
  MEDIUM: {
    bg: 'bg-amber-50/70 dark:bg-amber-950/30',
    text: 'text-amber-700 dark:text-amber-400',
    border: 'border-amber-200 dark:border-amber-900/60',
    icon: <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400" />
  },
  LOW: {
    bg: 'bg-blue-50/70 dark:bg-blue-950/30',
    text: 'text-blue-700 dark:text-blue-400',
    border: 'border-blue-200 dark:border-blue-900/60',
    icon: <Info className="w-4 h-4 text-blue-600 dark:text-blue-400" />
  },
  INFO: {
    bg: 'bg-slate-50 dark:bg-slate-900/80',
    text: 'text-slate-600 dark:text-slate-400',
    border: 'border-slate-200 dark:border-slate-800',
    icon: <CheckCircle2 className="w-4 h-4 text-slate-500 dark:text-slate-400" />
  }
};

export const UnifiedScanReport: React.FC<UnifiedScanReportProps> = ({ scan, onNavigateTab }) => {
  const [copied, setCopied] = useState(false);
  const [findingSeverityFilter, setFindingSeverityFilter] = useState<string>('ALL');

  const scrollTo = (elementId: string) => {
    const el = document.getElementById(elementId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const getGradeColor = (grade: string) => {
    switch (grade) {
      case 'A+':
      case 'A':
        return 'text-emerald-700 dark:text-emerald-400 border-emerald-300 dark:border-emerald-700 bg-emerald-50 dark:bg-emerald-950/40';
      case 'B':
        return 'text-blue-700 dark:text-blue-400 border-blue-300 dark:border-blue-700 bg-blue-50 dark:bg-blue-950/40';
      case 'C':
        return 'text-amber-700 dark:text-amber-400 border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-950/40';
      default:
        return 'text-red-700 dark:text-red-400 border-red-300 dark:border-red-700 bg-red-50 dark:bg-red-950/40';
    }
  };

  const handleCopySummary = () => {
    const markdown = `# External Attack Surface Assessment: ${scan.domain}
- **Scan Timestamp:** ${new Date(scan.scannedAt).toUTCString()}
- **Attack Surface Posture Score:** ${scan.overallScore}/100 (Grade: ${scan.grade})
- **Discovered Subdomains:** ${scan.subdomains.length}
- **Public Certificates:** ${scan.certificates.length}
- **Primary Hosting:** ${scan.network.hostingType || 'Standard'} (${scan.network.asn || 'N/A'})
- **Email Security:** DMARC=${scan.dns.emailSecurity.dmarc.status} (${scan.dns.emailSecurity.dmarc.policy || 'none'}), SPF=${scan.dns.emailSecurity.spf.status}

## Key Findings (${scan.findings.length} total):
${scan.findings.map(f => `- [${f.severity}] ${f.title} (MITRE: ${f.mitre.id} - ${f.mitre.name})`).join('\n')}

---
Generated by SurfaceTrace EASM
`;
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const filteredFindings = scan.findings.filter(f => 
    findingSeverityFilter === 'ALL' || f.severity === findingSeverityFilter
  );

  return (
    <div className="space-y-8 pb-16">
      {/* 1. Executive Summary Banner */}
      <section id="section-summary" className="scroll-mt-28">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-8 shadow-xs transition-colors">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
            {/* Target Identity & Metadata */}
            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 border border-blue-200 dark:border-blue-800">
                  ASSESSMENT TARGET
                </span>
                <span className="text-xs font-mono text-slate-500 dark:text-slate-400">
                  Scanned: {new Date(scan.scannedAt).toLocaleString()}
                </span>
                <span className="text-xs font-mono text-slate-500 dark:text-slate-400">
                  Apex IP: <code className="font-bold text-slate-800 dark:text-slate-200">{scan.network.ip || 'Unresolved'}</code>
                </span>
              </div>

              <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
                {scan.domain}
              </h1>

              <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 max-w-2xl leading-relaxed">
                Autonomous reconnaissance identified <strong className="text-slate-900 dark:text-white">{scan.subdomains.length} exposed assets</strong> and <strong className="text-slate-900 dark:text-white">{scan.findings.length} security exposure points</strong> across public DNS, TLS transport, and mail authentication vectors.
              </p>

              {/* Action Buttons */}
              <div className="pt-2 flex flex-wrap gap-2">
                <button
                  onClick={handleCopySummary}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-medium border border-slate-200 dark:border-slate-700 transition-colors cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
                  <span>{copied ? 'Copied Briefing' : 'Copy Executive Briefing'}</span>
                </button>

                <button
                  onClick={() => onNavigateTab('sqlite')}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-50 hover:bg-emerald-100 dark:bg-emerald-950/40 dark:hover:bg-emerald-900/60 text-emerald-700 dark:text-emerald-300 text-xs font-medium border border-emerald-200 dark:border-emerald-800 transition-colors cursor-pointer"
                >
                  <Terminal className="w-3.5 h-3.5" />
                  <span>Inspect In SQLite Vault</span>
                </button>

                <button
                  onClick={() => window.print()}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-medium border border-slate-200 dark:border-slate-700 transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-slate-500" />
                  <span>Print Report</span>
                </button>
              </div>
            </div>

            {/* Score & Grade Display */}
            <div className="flex items-center gap-4 bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 p-5 rounded-2xl shrink-0">
              <div className={`w-16 h-16 rounded-xl border-2 flex items-center justify-center font-extrabold text-2xl ${getGradeColor(scan.grade)}`}>
                {scan.grade}
              </div>
              <div className="space-y-1">
                <div className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                  Security Posture Score
                </div>
                <div className="text-3xl font-extrabold font-mono text-slate-900 dark:text-white">
                  {scan.overallScore}<span className="text-slate-400 text-lg font-normal">/100</span>
                </div>
                <div className="text-[11px] text-slate-500 dark:text-slate-400">
                  Calculated against NIST & CIS hygiene criteria
                </div>
              </div>
            </div>
          </div>

          {/* 5 Core Dimensions Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4 mt-6 pt-6 border-t border-slate-100 dark:border-slate-800/80">
            {/* Card 1: Subdomains */}
            <div 
              onClick={() => scrollTo('section-footprint')} 
              className="bg-slate-50/70 dark:bg-slate-950/40 hover:bg-white dark:hover:bg-slate-850 hover:border-blue-300 dark:hover:border-blue-700 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-1.5">
                <span className="text-xs font-semibold uppercase tracking-wider">Discovered Subdomains</span>
                <Globe className="w-4 h-4 text-blue-600 dark:text-blue-400 group-hover:translate-x-0.5 transition-transform" />
              </div>
              <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white">
                {scan.subdomains.length}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-1">
                <span>View asset inventory</span>
                <ArrowDown className="w-3 h-3 text-blue-500" />
              </p>
            </div>

            {/* Card 2: Certificates */}
            <div 
              onClick={() => scrollTo('section-footprint')} 
              className="bg-slate-50/70 dark:bg-slate-950/40 hover:bg-white dark:hover:bg-slate-850 hover:border-blue-300 dark:hover:border-blue-700 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-1.5">
                <span className="text-xs font-semibold uppercase tracking-wider">Public TLS Certs</span>
                <Lock className="w-4 h-4 text-blue-600 dark:text-blue-400 group-hover:translate-x-0.5 transition-transform" />
              </div>
              <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white">
                {scan.certificates.length}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-1">
                <span>Logged in CT registries</span>
                <ArrowDown className="w-3 h-3 text-blue-500" />
              </p>
            </div>

            {/* Card 3: DMARC / SPF */}
            <div 
              onClick={() => scrollTo('section-posture')} 
              className="bg-slate-50/70 dark:bg-slate-950/40 hover:bg-white dark:hover:bg-slate-850 hover:border-blue-300 dark:hover:border-blue-700 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-1.5">
                <span className="text-xs font-semibold uppercase tracking-wider">DMARC / Mail Auth</span>
                <Mail className="w-4 h-4 text-blue-600 dark:text-blue-400 group-hover:translate-x-0.5 transition-transform" />
              </div>
              <div className="text-sm font-semibold capitalize">
                {scan.dns.emailSecurity.dmarc.status === 'enforced' ? (
                  <span className="text-emerald-700 dark:text-emerald-400 flex items-center gap-1 font-medium">
                    <CheckCircle2 className="w-4 h-4" /> Enforced ({scan.dns.emailSecurity.dmarc.policy})
                  </span>
                ) : scan.dns.emailSecurity.dmarc.status === 'monitoring_only' ? (
                  <span className="text-amber-700 dark:text-amber-400 flex items-center gap-1 font-medium">
                    <AlertTriangle className="w-4 h-4" /> Monitoring (p=none)
                  </span>
                ) : (
                  <span className="text-red-700 dark:text-red-400 flex items-center gap-1 font-medium">
                    <ShieldAlert className="w-4 h-4" /> Missing DMARC
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-1">
                <span>Inspect mail policies</span>
                <ArrowDown className="w-3 h-3 text-blue-500" />
              </p>
            </div>

            {/* Card 4: Leaked Credentials & Stealers */}
            <div 
              onClick={() => scrollTo('section-vulnerabilities')} 
              className="bg-slate-50/70 dark:bg-slate-950/40 hover:bg-white dark:hover:bg-slate-900 hover:border-red-300 dark:hover:border-red-700 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-1.5">
                <span className="text-xs font-semibold uppercase tracking-wider">Credential Leaks</span>
                <Flame className="w-4 h-4 text-red-500 group-hover:scale-110 transition-transform" />
              </div>
              <div className="text-sm font-bold truncate">
                {scan.vulnerabilities?.employeeLoginsCompromised ? (
                  <span className="text-red-600 dark:text-red-400 flex items-center gap-1">
                    <Bug className="w-3.5 h-3.5 shrink-0" />
                    <span>{scan.vulnerabilities.employeeLoginsCompromised} Stealer Hosts</span>
                  </span>
                ) : (scan.vulnerabilities?.breaches?.length || 0) > 0 ? (
                  <span className="text-orange-600 dark:text-orange-400">
                    {scan.vulnerabilities?.breaches.length} Public Breach{scan.vulnerabilities?.breaches.length! > 1 ? 'es' : ''}
                  </span>
                ) : (
                  <span className="text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" /> Clean Baseline
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-1">
                <span>HIBP & Stealer Feeds</span>
                <ArrowDown className="w-3 h-3 text-red-500" />
              </p>
            </div>

            {/* Card 5: ASN */}
            <div 
              onClick={() => scrollTo('section-footprint')} 
              className="bg-slate-50/70 dark:bg-slate-950/40 hover:bg-white dark:hover:bg-slate-900 hover:border-blue-300 dark:hover:border-blue-700 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-1.5">
                <span className="text-xs font-semibold uppercase tracking-wider">Routing & ASN</span>
                <Server className="w-4 h-4 text-blue-600 dark:text-blue-400 group-hover:translate-x-0.5 transition-transform" />
              </div>
              <div className="text-sm font-bold font-mono text-slate-900 dark:text-white truncate">
                {scan.network.asn || 'Private / Unknown'}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 truncate">
                {scan.network.asOrganization || 'Global edge routing'}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Sticky Section Anchor Navigation Bar */}
      <nav aria-label="Report Section Navigation" className="sticky top-16 z-30 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md border border-slate-200 dark:border-slate-800 p-2 rounded-xl shadow-xs transition-colors flex items-center justify-between gap-2 overflow-x-auto">
        <div className="flex items-center gap-1.5 shrink-0 text-xs">
          <button
            onClick={() => scrollTo('section-summary')}
            className="px-3 py-1.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors cursor-pointer whitespace-nowrap"
          >
            1. Overview
          </button>
          <button
            onClick={() => scrollTo('section-vulnerabilities')}
            className="px-3 py-1.5 rounded-lg text-red-700 dark:text-red-300 bg-red-50/80 dark:bg-red-950/50 hover:bg-red-100 dark:hover:bg-red-900/60 font-semibold transition-colors cursor-pointer whitespace-nowrap flex items-center gap-1.5 border border-red-200/80 dark:border-red-800/80"
          >
            <Flame className="w-3.5 h-3.5 text-red-600 dark:text-red-400" />
            <span>2. Vulnerabilities & Leaks</span>
            {((scan.vulnerabilities?.employeeLoginsCompromised || 0) > 0 || (scan.vulnerabilities?.breaches?.length || 0) > 0) && (
              <span className="px-1.5 py-0.2 rounded-full text-[10px] bg-red-600 text-white font-bold">
                {(scan.vulnerabilities?.employeeLoginsCompromised || 0) + (scan.vulnerabilities?.breaches?.length || 0)}
              </span>
            )}
          </button>
          <button
            onClick={() => scrollTo('section-findings')}
            className="px-3 py-1.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors cursor-pointer whitespace-nowrap flex items-center gap-1.5"
          >
            <span>3. Findings</span>
            <span className="px-1.5 py-0.2 rounded-full text-[10px] bg-red-500 text-white font-bold">
              {scan.findings.length}
            </span>
          </button>
          <button
            onClick={() => scrollTo('section-mitre')}
            className="px-3 py-1.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors cursor-pointer whitespace-nowrap"
          >
            4. MITRE ATT&CK Matrix
          </button>
          <button
            onClick={() => scrollTo('section-footprint')}
            className="px-3 py-1.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors cursor-pointer whitespace-nowrap"
          >
            5. Digital Footprint ({scan.subdomains.length})
          </button>
          <button
            onClick={() => scrollTo('section-posture')}
            className="px-3 py-1.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors cursor-pointer whitespace-nowrap"
          >
            6. Security Posture & Controls
          </button>
          <button
            onClick={() => scrollTo('section-compliance')}
            className="px-3 py-1.5 rounded-lg text-purple-700 dark:text-purple-300 bg-purple-50/70 dark:bg-purple-950/40 hover:bg-purple-100 dark:hover:bg-purple-900/60 font-semibold transition-colors cursor-pointer whitespace-nowrap flex items-center gap-1.5 border border-purple-200/80 dark:border-purple-800/80"
          >
            <Scale className="w-3.5 h-3.5 text-purple-600 dark:text-purple-400" />
            <span>7. NIST & Compliance</span>
          </button>
          <button
            onClick={() => scrollTo('section-ai')}
            className="px-3 py-1.5 rounded-lg text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/60 font-semibold transition-colors cursor-pointer whitespace-nowrap flex items-center gap-1"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>8. AI Threat Simulation</span>
          </button>
        </div>

        <div className="hidden md:flex items-center text-[11px] font-mono text-slate-400 pr-2 shrink-0">
          <span>Scroll down for complete audit</span>
        </div>
      </nav>

      {/* 2. Vulnerabilities & Leaked Credentials Section */}
      <section id="section-vulnerabilities" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Flame className="w-5 h-5 text-red-600 dark:text-red-400" />
              Vulnerabilities & Leaked Credential Intelligence
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Live intelligence feeds from Have I Been Pwned, Hudson Rock Cavalier stealer logs, and Git secret exposure vectors
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <VulnerabilitiesTab scan={scan} initialData={scan.vulnerabilities} />
      </section>

      {/* 3. Prioritized Security Findings Section */}
      <section id="section-findings" className="scroll-mt-28 space-y-4">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-8 shadow-xs space-y-5 transition-colors">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <ShieldAlert className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                Prioritized Attack Surface Findings & Exposure Points
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Deterministic security analysis correlated with MITRE ATT&CK Enterprise techniques & Statutory Regulatory Controls (NIST SP 800-53, CIS v8, ISO 27001, PCI-DSS)
              </p>
            </div>

            {/* Severity Breakdown Badges & Filter */}
            <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
              <button
                onClick={() => setFindingSeverityFilter('ALL')}
                className={`px-2.5 py-1 rounded-md transition-colors cursor-pointer ${findingSeverityFilter === 'ALL' ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900 font-bold' : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300'}`}
              >
                All ({scan.findings.length})
              </button>
              {scan.summary.criticalCount > 0 && (
                <button
                  onClick={() => setFindingSeverityFilter('CRITICAL')}
                  className={`px-2 py-0.5 rounded border transition-colors cursor-pointer ${findingSeverityFilter === 'CRITICAL' ? 'bg-red-600 text-white border-red-700' : 'bg-red-50 dark:bg-red-950/60 text-red-700 dark:text-red-300 border-red-200 dark:border-red-800 font-semibold'}`}
                >
                  {scan.summary.criticalCount} Critical
                </button>
              )}
              {scan.summary.highCount > 0 && (
                <button
                  onClick={() => setFindingSeverityFilter('HIGH')}
                  className={`px-2 py-0.5 rounded border transition-colors cursor-pointer ${findingSeverityFilter === 'HIGH' ? 'bg-orange-600 text-white border-orange-700' : 'bg-orange-50 dark:bg-orange-950/60 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-800 font-semibold'}`}
                >
                  {scan.summary.highCount} High
                </button>
              )}
              {scan.summary.mediumCount > 0 && (
                <button
                  onClick={() => setFindingSeverityFilter('MEDIUM')}
                  className={`px-2 py-0.5 rounded border transition-colors cursor-pointer ${findingSeverityFilter === 'MEDIUM' ? 'bg-amber-600 text-white border-amber-700' : 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800 font-semibold'}`}
                >
                  {scan.summary.mediumCount} Medium
                </button>
              )}
              {scan.summary.lowCount > 0 && (
                <button
                  onClick={() => setFindingSeverityFilter('LOW')}
                  className={`px-2 py-0.5 rounded border transition-colors cursor-pointer ${findingSeverityFilter === 'LOW' ? 'bg-blue-600 text-white border-blue-700' : 'bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800 font-semibold'}`}
                >
                  {scan.summary.lowCount} Low
                </button>
              )}
            </div>
          </div>

          {filteredFindings.length === 0 ? (
            <div className="text-center py-12 text-slate-500 dark:text-slate-400 space-y-2">
              <ShieldCheck className="w-12 h-12 text-emerald-600 dark:text-emerald-400 mx-auto" />
              <p className="font-semibold text-slate-800 dark:text-slate-200 text-sm">
                No exposure points match the selected filter.
              </p>
              <p className="text-xs text-slate-500">
                The public perimeter shows compliant configurations for these criteria.
              </p>
            </div>
          ) : (
            <div className="space-y-3.5">
              {filteredFindings.map((finding) => {
                const sev = SEVERITY_CONFIG[finding.severity] || SEVERITY_CONFIG.INFO;
                return (
                  <div
                    key={finding.id}
                    className={`p-4 sm:p-5 rounded-xl border ${sev.border} ${sev.bg} transition-all space-y-3`}
                  >
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <div className="flex items-center space-x-2.5">
                        {sev.icon}
                        <span className="font-bold text-sm text-slate-900 dark:text-slate-100">
                          {finding.title}
                        </span>
                        <span className={`text-[10px] uppercase font-mono px-2 py-0.5 rounded font-bold border ${sev.border} ${sev.text}`}>
                          {finding.severity}
                        </span>
                      </div>

                      {/* MITRE ATT&CK Tag - Scrolls right down to matrix */}
                      <button
                        onClick={() => scrollTo('section-mitre')}
                        className="self-start sm:self-auto inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-[11px] font-mono text-slate-700 dark:text-slate-200 border border-slate-300 dark:border-slate-700 transition-colors cursor-pointer shadow-xs"
                        title="Jump to technique in MITRE ATT&CK Matrix below"
                      >
                        <Layers className="w-3 h-3 text-blue-600 dark:text-blue-400" />
                        <span>{finding.mitre.id}: {finding.mitre.name}</span>
                        <ArrowDown className="w-3 h-3 text-slate-400" />
                      </button>
                    </div>

                    <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                      {finding.description}
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1 text-xs font-mono">
                      <div className="p-3 rounded-lg bg-white/90 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800">
                        <span className="text-slate-500 dark:text-slate-400 block text-[10px] uppercase font-bold tracking-wider mb-1">Discovered Evidence</span>
                        <span className="text-slate-800 dark:text-slate-200 break-all">{finding.evidence}</span>
                      </div>
                      <div className="p-3 rounded-lg bg-white/90 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800">
                        <span className="text-emerald-700 dark:text-emerald-400 block text-[10px] uppercase font-bold tracking-wider mb-1">Remediation Action</span>
                        <span className="text-slate-800 dark:text-slate-200">{finding.remediation}</span>
                      </div>
                    </div>

                    {/* Deterministic Compliance Controls Mapping */}
                    {(() => {
                      const controls = getControlsForFinding(finding.id, finding.complianceControls);
                      if (!controls || controls.length === 0) return null;

                      return (
                        <div className="pt-2 border-t border-slate-200/60 dark:border-slate-800/60 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                          <div className="flex flex-wrap items-center gap-1.5">
                            <span className="text-[10px] uppercase font-bold tracking-wider text-purple-700 dark:text-purple-400 flex items-center gap-1 shrink-0 font-mono">
                              <Scale className="w-3 h-3" />
                              Statutory Controls:
                            </span>
                            {controls.map((ctrl, idx) => (
                              <button
                                key={idx}
                                onClick={() => scrollTo('section-compliance')}
                                title={`${ctrl.frameworkLabel} - ${ctrl.controlName}. Click to inspect full audit report.`}
                                className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-purple-50 hover:bg-purple-100 dark:bg-purple-950/60 dark:hover:bg-purple-900/60 text-purple-800 dark:text-purple-300 border border-purple-200 dark:border-purple-800/80 text-[10px] font-mono font-semibold transition-colors cursor-pointer"
                              >
                                <span>{ctrl.controlId}</span>
                              </button>
                            ))}
                          </div>
                          <button
                            onClick={() => scrollTo('section-compliance')}
                            className="text-[11px] font-medium text-purple-600 dark:text-purple-400 hover:underline inline-flex items-center gap-1 cursor-pointer self-start sm:self-auto shrink-0"
                          >
                            <span>Audit Citations</span>
                            <ArrowDown className="w-3 h-3" />
                          </button>
                        </div>
                      );
                    })()}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </section>

      {/* 3. MITRE ATT&CK Matrix Section */}
      <section id="section-mitre" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Layers className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              MITRE ATT&CK® Enterprise Matrix Correlation
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Adversary TTP mappings for Reconnaissance (TA0043) and Initial Access (TA0001)
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <MitreMatrixTab scan={scan} />
      </section>

      {/* 4. Digital Footprint & Asset Inventory Section */}
      <section id="section-footprint" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Globe className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              Digital Footprint & Discovered Assets
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Public subdomains, DNS zone records, Certificate Transparency chains, and WHOIS registration
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <DigitalFootprintTab scan={scan} />
      </section>

      {/* 5. Security Posture & Controls Section */}
      <section id="section-posture" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Shield className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              Security Posture & Defensive Controls
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              DMARC/SPF email spoofing defense, HTTP transport headers, cookie flags, and subdomain takeover risk
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <SecurityPostureTab scan={scan} onNavigateTab={onNavigateTab} />
      </section>

      {/* 6. Regulatory & Benchmark Compliance Audit Section */}
      <section id="section-compliance" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Scale className="w-5 h-5 text-purple-600 dark:text-purple-400" />
              NIST & Regulatory Compliance Audit Report
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Automated audit against NIST SP 800-53 Rev. 5, NIST CSF v2.0, CIS Controls v8, ISO/IEC 27001, and PCI-DSS v4.0
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <ComplianceReportTab scan={scan} />
      </section>

      {/* 7. AI Adversary Threat Simulation Section */}
      <section id="section-ai" className="scroll-mt-28 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              AI Threat Simulation & Red-Team Scenario Modeling
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Synthesized adversary initial access pathway and CIS Controls v8 hardening roadmap
            </p>
          </div>
          <button 
            onClick={() => scrollTo('section-summary')}
            className="text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer hidden sm:block"
          >
            ↑ Top of report
          </button>
        </div>
        <AiThreatReportTab scan={scan} />
      </section>
    </div>
  );
};
